name: Build and Pack eServiceOnline UAT

on:
  pull_request:
    branches:
      - test    

  push:       
    branches:
      - test   
  
  workflow_dispatch:
      
defaults:
  run:
    shell: pwsh
    working-directory: Source
    
jobs:
  Build-and-Pack-UAT: 

    environment:
      name: 'uat'
    
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'eServiceOnline.sln'

    #runs-on: self-hosted
    runs-on: windows-2019
    
    permissions:
      packages: write
      actions: write
      checks: write
      contents: read
      
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true

#--set variables

    - name: print
      run:  |
        echo "${{ secrets.eServiceOnline_ConnectionStrings_DefaultConnString }}" ;
        

    - name: Update eServiceOnline Variables
      uses: microsoft/variable-substitution@v1
      with:
        files: 'source/eServiceOnline/app.config, source/eServiceOnline/appsettings.json'
      env:
        connectionString: ${{ secrets.eServiceOnline_ConnectionStrings_SanjelData }}
        ConnectionStrings.SanjelData: ${{ secrets.eServiceOnline_ConnectionStrings_SanjelData }}
        applicationContext: ${{ vars.eServiceOnline_applicationContext }}
        EServiceApiAddress: ${{ vars.eServiceOnline_EServiceApiAddress }}
        cachePath: ${{ vars.eServiceOnline_cachePath }}       
        enableDirectInvoke: ${{ vars.eServiceOnline_enableDirectInvoke }}       
        timeInterval: ${{ vars.eServiceOnline_timeInterval }}       
        printOutFilePath: ${{ vars.eServiceOnline_printOutFilePath }}
        SendCrewNotification: ${{ vars.eServiceOnline_SendCrewNotification }}
        CustomLogging.WriteTo.0.Args.configure.0.Args.rootPath: ${{ vars.eServiceOnline_CustomLoggingWriteTorootPath }}
        Notifications.SendNotificationURL: ${{ secrets.eServiceOnline_NotificationsSendNotificationURL }}
        Notifications.Environment: ${{ vars.eServiceOnline_NotificationsEnvironment }}
        Notifications.SecretKey: ${{ secrets.eServiceOnline_NotificationsSecretKey }}

#--end set variables

 
        
    - name: Upload files
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v4
      with:
        name: resultAPPconfigInstaller
        path: .
        retention-days: 1
        compression-level: 1 

    - name: Upload UAT Setup
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v4
      with:
        name: eServiceExpress UAT Setup
        path: Source/Deploy/Output/*uat*.exe
        retention-days: 30
        compression-level: 0        
        
    #- name: Publish Test Results
    #  uses: dorny/test-reporter@v1.6.0
    #  if: ${{ always() }}
    #  with:
    #    name: Unit Tests
    #    path: ${{ env.RUNNER_TEMP }}/TestResults/*.trx
    #    reporter: dotnet-trx
    #    fail-on-error: true
